FROM node:16

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm install

RUN npm install -g @nestjs/cli

COPY server ./server

EXPOSE 3011

CMD ["npm", "run", "start", "--prefix", "server"]
