# Компиляция Angular приложения
FROM node:16 AS angular-build
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm install

# Установка Angular CLI
RUN npm install -g @angular/cli

# Копирование и сборка Angular приложения
COPY client ./client
WORKDIR /app/client
RUN ng build --prod

FROM nginx:alpine
COPY --from=angular-build /app/client/dist/client /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
