FROM node:16 AS angular-build

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm install

RUN npm install -g @angular/cli

COPY client ./client
WORKDIR /app/client
RUN npm install

# Собираем проект
RUN ng build --prod

FROM nginx:alpine
COPY --from=angular-build /app/client/dist/client /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
